<a href="https://colab.research.google.com/github/leonardoLavagna/PyTorch-Notebooks/blob/main/Notebook_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Notebook 1
## Fundamentals
In this first notebook we will start familiarizing with PyTorch and its fundamentals.

## Setup

In [ ]:
# GPU Info (in Google Colab)
# !nvidia-smi

In [ ]:
import torch
print(torch.__version__)

1.12.1+cu113


## Tensors
Tensors are the main buildin blocks of deep learning. In particular tensors are used to represent (numerical) data in PyTorch. There are many types of tensors with different dimensions (e.g. scalars, vectors, matrixes,...) and they are usually created using `torch.tensor()` (see https://pytorch.org/docs/stable/tensors.html).

In [ ]:
# Create an empty tensor (scalar)
# Remark . An empty tensor is usually not initialized.
x = torch.empty(1)
print(x)
# For a scalar tensor x we can get the tensor value with x.item()
print(x.item())
# default type
print(x.dtype)
# dimension and shape
print(x.ndim)
print(x.shape)

tensor([1.0148e-35])
1.0147546818969555e-35
torch.float32
1
torch.Size([1])


In [ ]:
# Create a specific tensor (scalar) with a different data type
x = torch.tensor(1,dtype=torch.int32)
print(x)
print(x.item())
print(x.dtype)

tensor(1, dtype=torch.int32)
1
torch.int32


**Remark .** The default datatype of a tensor is `float32`. This can be changed in many other data types: `int32, float16, complex 64`... see https://pytorch.org/docs/stable/tensors.html for all the data types available. 

In [ ]:
# Create a vector with all zeros
x = torch.zeros(2)
print(x)
print(x.ndim)
print(x.shape)

tensor([0., 0.])
1
torch.Size([2])


In [ ]:
# Create a 2x2 matrix with all ones
x = torch.ones(2,2)
print(x)
print(x.ndim)
print(x.shape)

tensor([[1., 1.],
        [1., 1.]])
2
torch.Size([2, 2])


In [ ]:
# Access elements
print(x[1])
print(x[1][1])

tensor([1., 1.])
tensor(1.)


In [ ]:
# Create a tensor (1 tensor 2x3)
x = torch.tensor([[[1,2,3],[4,5,6]]])
print(x)
print(x.ndim)
print(x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]])
3
torch.Size([1, 2, 3])


In [ ]:
# Create a random tensor
# Random seed (for this block)
random_seed = 1234
torch.manual_seed(random_seed)
# Random tensor
x = torch.rand(1,2,3,3)
print(x)
print(x.ndim)
print(x.shape)

tensor([[[[0.0290, 0.4019, 0.2598],
          [0.3666, 0.0583, 0.7006],
          [0.0518, 0.4681, 0.6738]],

         [[0.3315, 0.7837, 0.5631],
          [0.7749, 0.8208, 0.2793],
          [0.6817, 0.2837, 0.6567]]]])
4
torch.Size([1, 2, 3, 3])


In [ ]:
# Access elements
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][0][0][0])

tensor([[[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006],
         [0.0518, 0.4681, 0.6738]],

        [[0.3315, 0.7837, 0.5631],
         [0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006],
        [0.0518, 0.4681, 0.6738]])
tensor([0.0290, 0.4019, 0.2598])
tensor(0.0290)


**Remark .** In many neural networks random tensors are very important because they often learn by strating with a random tensor and updating it adjusting the values to better represent or fit the data.

In [ ]:
# Create a tensor-range (default start=0, end=length-1, step=1)
range = torch.arange(start=0,end=10,step=2)
print(range)

tensor([0, 2, 4, 6, 8])


In [ ]:
# Creating tensors like the previous one but with all zeros
tensor_like = torch.zeros_like(input=range)
print(tensor_like)

tensor([0, 0, 0, 0, 0])


## Slicing and reshaping
Slicing is very similar to the same operation with python arrays, and reshaping can be done with the function `torch.tensor.view()`, see https://pytorch.org/docs/stable/generated/torch.Tensor.view.html.

In [ ]:
# Slicing
x = torch.rand(4,4)
print(x)
print(x[:,0])
print(x[0,0])
print(x[1,1].item())

tensor([[0.2388, 0.7313, 0.6012, 0.3043],
        [0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525],
        [0.6662, 0.3343, 0.7893, 0.3216]])
tensor([0.2388, 0.2548, 0.4517, 0.6662])
tensor(0.2388)
0.6293618679046631


In [ ]:
# Reshaping
print(x.size())

y = x.view(16)
print(y)
print(y.size())

y = x.view(-1,8)
print(y)
print(y.size())

torch.Size([4, 4])
tensor([0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517,
        0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216])
torch.Size([16])
tensor([[0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216]])
torch.Size([2, 8])


## Aritmetic operations with tensors
Aritmetic operations between tensors are very similar to aritmetic operations with arrays (e.g. in `numpy`)

In [ ]:
# Elementwise addition of tensors with the same size
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a+b
print(a)
print(b)
print(c)

tensor([[0.5247, 0.6688],
        [0.8436, 0.4265]])
tensor([[0.9561, 0.0770],
        [0.4108, 0.0014]])
tensor([[1.4809, 0.7458],
        [1.2544, 0.4279]])


In [ ]:
# same as before
print(torch.add(a,b))

tensor([[1.4809, 0.7458],
        [1.2544, 0.4279]])


In [ ]:
# inplace addition, same as before
# all pytorch function with _ at the end are usually inplace operations
print(b.add_(a))

tensor([[1.4809, 0.7458],
        [1.2544, 0.4279]])


All the other aritmetic operations are carried out in a similar fashion. In particular we have:


*   **elementwise subtraction** `a-b` or `torch.sub(a,b)` or `a.sub_(b)`;
*   **elementwise multiplication** `a*b` or `torch.mul(a,b)` or `a.mul_(b)`;
*   **elementwise division** ` a / b ` or `torch.div(a,b)` or `a.div_(b)`;
*   **elementwise power** ` a**b ` or `torch.pow(a,b)` or `a.pow_(b)`;

See https://pytorch.org/docs/stable/torch.html for all the other useful operations.

**Remark .** The device where a tensor is saved is of crucial importance as the following code shows.

In [ ]:
# Create a tensor 
x = torch.ones(5)
print(x)
# Move it in the GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = x.to(device)
  print(x)

# Move the tensor in the CPU
x = x.to("cpu")
# Change the tensor in the CPU
# Note that x+=1 is the same as x=x+1
x += 1
print(x)

# Also the tensor in the GPU has been changed!
if torch.cuda.is_available():
  x = x.to(device)
  print(x)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])
tensor([2., 2., 2., 2., 2.], device='cuda:0')


## From Numpy to PyThorch and back
Many operations between tensors (e.g. matrix multiplications) are particularly easy to carry out with `numpy`, see https://numpy.org. To convert a tensor to a numpy array, and vicerversa, we can use the following code. 

In [ ]:
import numpy as np

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# From PyThorch to Numpy
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# From Numpy to PyThorch
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


**Remark .** At the time of writing `numpy` works only with CPUs. 

## Exercises


1.   Create a random tensor `a` with shape (4,4) and perform a matrix multiplication with another random tensor `b` with shape (1, 4) (hint: you may have to transpose the second tensor).
2.   Find the maximum and minimum values of the output of the matrix multiplication of `a` and `b` created in the previous exercise.
3.   Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: look into the documentation for `torch.cuda` for this one). 

